### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [Toilal/oika-automator#1]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/pragmasphere/oika/automator/security/SecurityServiceImpl.java: Line number => 32: API name => Cipher:<BR> File name => src/main/java/com/pragmasphere/oika/automator/security/SecurityServiceImpl.java: Line number => 32: API name => Cipher:<BR> File name => src/main/java/com/pragmasphere/oika/automator/security/SecurityServiceImpl.java: Line number => 16: API name => SecretKeySpec:<BR> File name => src/main/java/com/pragmasphere/oika/automator/security/SecurityServiceImpl.java: Line number => 45: API name => Cipher:<BR> File name => src/main/java/com/pragmasphere/oika/automator/security/SecurityServiceImpl.java: Line number => 43: API name => Cipher:<BR> File name => src/main/java/com/pragmasphere/oika/automator/security/SecurityServiceImpl.java: Line number => 30: API name => Cipher:<BR> File name => src/main/java/com/pragmasphere/oika/automator/security/SecurityServiceImpl.java: Line number => 45: API name => Cipher:<BR> File name => src/main/java/com/pragmasphere/oika/automator/security/SecurityServiceImpl.java: Line number => 16: API name => SecretKeySpec:<BR>

**Comment by Toilal** [comment]
Thanks, I know, no problem with this it's allow to encrypt a password in a configuration file.
